services:
  - type: web
    runtime: node
    name: medisync-api
    plan: free
    rootDir: backend
    autoDeploy: true
    healthCheckPath: /api/health
    buildCommand: npm install --include=dev && npm run prisma:generate && npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://educore_postgres_user:2jdFNpFi14WY4dKM7cJNrlS2c9A6Qb8P@dpg-d7ej8f77f7vs73d7qr7g-a/educore_postgres
      - key: JWT_SECRET
        value: 911e780a6ee64907adbc63045eb0f934a113a7cbcfc89c498853c23c9b26688e73d411130da6fc7d5fd9497a0431e2b0
      - key: CORS_ORIGIN
        value: https://medisync-web-925n.onrender.com

  - type: web
    runtime: static
    name: medisync-web
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://medisync-api-925n.onrender.com/api
